=== rektide/jstyx/core/conf/styxSecurity.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary indentification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/serverConfig.dtd

-->

<!--- The root element of the document -->
<!ELEMENT security (server, users, groups)>

<!--- Sets the port on which the server will listen and whether or not 
      authentication is required -->
<!ELEMENT server (ssl?)>
<!ATTLIST server
    allowAnonymousLogin (true|false) "false"
    useSSL (true|false) "false"
  >
<!--- Sets up SSL - gives location and password of keystore -->
<!ELEMENT ssl EMPTY>
<!ATTLIST ssl
    keystore CDATA #REQUIRED
    password CDATA #REQUIRED
  >

<!ELEMENT users (user)*>
<!--- Describes a user.  Must have a username and password, email address is optional -->
<!ELEMENT user (password, fullName?)>
<!ATTLIST user
    name CDATA #REQUIRED
  >
<!ELEMENT password (#PCDATA)>
<!ELEMENT fullName (#PCDATA)>

<!--- A group of users -->
<!ELEMENT groups (group)*>
<!ELEMENT group (username)*>
<!ATTLIST group
    name CDATA #REQUIRED
  >
<!ELEMENT username (#PCDATA)>

=== rektide/jstyx/core/conf/styxSecurity.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : serverConfig.xml
    Created on : 20 March 2006, 11:24
    Author     : jdb
    Description:
        Example config file for a Styx server.  Defines the users that are allowed
        to connect, etc.
-->

<!DOCTYPE security SYSTEM "styxSecurity.dtd">

<security>
    
    <server allowAnonymousLogin="false" useSSL="false"/>
    
    <users>
        <user name="jdb">
            <password>blower</password>
            <fullName>Jon Blower</fullName>
        </user>
        <user name="fred">
            <password>bloggs</password>
            <fullName>Fred Bloggs</fullName>
        </user>
    </users>
    
    <groups>
        <group name="admins">
            <username>jdb</username>
        </group>
    </groups>

</security>
